version: "3"
services:
    wordpress:
        image: wordpress
        container_name: wordpress
        volumes:
            - ./wp:/var/www/html
        ports:
            - 1980:80
        networks:
            - wp
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        networks:
            - wp
        depends_on:
            - db
        ports:
            - 1970:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password

    db:
        image: mariadb
        container_name: mariadb
        volumes:
            - ./wp_data:/var/lib/mysql
        networks:
            - wp
        environment:
            MYSQL_ROOT_PASSWORD: password

networks:
    wp:
